# Generated by Django 4.2.25 on 2025-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['show_date', 'show_time'], 'verbose_name': 'Showtime', 'verbose_name_plural': 'Showtimes'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, help_text='Movie poster image', null=True, upload_to='movie_posters/'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='available_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='screen_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
